[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "sudo apt-get update && sudo apt-get install -y python3 python3-pip build-essential",
  "cd web && pnpm install --frozen-lockfile",
  "cd web && npx prisma generate --schema=../prisma/schema.prisma"
]

[phases.build]
cmds = ["cd web && pnpm run build"]

[start]
cmd = "cd web && pnpm run start"

